version: "3.9"

services:

  spring-docker-application-test-image:
    image: spring-docker-application-test-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: dockerDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume: